stages:
  data_processing:
    cmd: python -m src.components.data_processing
    deps:
      - src/components/data_processing.py
      - config/config.yaml
      - data/raw/images
      - data/raw/kidneyData.csv
    params:
      - data_processing.test_size
      - data_processing.random_state
      - data_processing.target_mapping
      - data_processing.relation_map
    outs:
      - data/final/train.csv
      - data/final/test.csv

  binary_base_model_building:
    cmd: python -m src.components.binaryclassification.binarybase_model
    deps:
      - src/components/binaryclassification/binarybase_model.py
      - config/config.yaml
    params:
      - basic_model_params.img_height
      - basic_model_params.img_width
      - binaryclass_model_params.metrics
      - binaryclass_model_params.loss
      - binaryclass_model_params.optimizer
      - binaryclass_model_params.learning_rate
    outs:
      - models/binaryclass/base_binary_model.keras

  binaryclass_training:
    cmd: python -m src.components.binaryclassification.binaryclass_training
    deps:
      - src/components/binaryclassification/binaryclass_training.py
      - config/config.yaml
    params:
      - binaryclass_model_params.batch_size
      - binaryclass_model_params.epochs
      - binaryclass_model_params.learning_rate
    outs:
      - models/binaryclass/trained_binary_model.keras

  
  binaryclass_evaluation:
    cmd: python -m src.components.binaryclassification.binarymodel_evaluation
    deps:
      - src/components/binaryclassification/binarymodel_evaluation.py
      - config/config.yaml
    params:
      - binaryclass_model_params.experiment_name
      - binaryclass_model_params.run_name


  multi_base_model_building:
    cmd: python -m src.components.multiclassification.multibase_model
    deps:
      - src/components/multiclassification/multibase_model.py
      - config/config.yaml
    params:
      - basic_model_params.img_height
      - basic_model_params.img_width
      - multiclass_model_params.metrics
      - multiclass_model_params.loss
      - multiclass_model_params.optimizer
      - multiclass_model_params.num_classes
      - multiclass_model_params.learning_rate
    outs:
      - models/multiclass/base_multi_model.keras

  multiclass_training:
    cmd: python -m src.components.multiclassification.multiclass_training
    deps:
      - src/components/multiclassification/multiclass_training.py
      - config/config.yaml
    params:
      - multiclass_model_params.batch_size
      - multiclass_model_params.epochs
      - multiclass_model_params.learning_rate
    outs:
      - models/multiclass/trained_multi_model.keras

  multiclass_evaluation:
      cmd: python -m src.components.multiclassification.multimodel_evaluation
      deps:
        - src/components/multiclassification/multimodel_evaluation.py
      params:
        - multiclass_model_params.experiment_name
        - multiclass_model_params.run_name
