stages:
  data_processing:
    cmd: python -m src.components.data_processing
    deps:
      - src/components/data_processing.py
      - config/config.yaml
      - data/raw/images
      - data/raw/kidneyData.csv
    params:
      - data_processing.test_size
      - data_processing.random_state
      - data_processing.target_mapping
      - data_processing.relation_map
    outs:
      - data/final/train.csv
      - data/final/test.csv

  model_building:
    cmd: python -m src.components.model_building
    deps:
      - src/components/model_building.py
      - config/config.yaml
    params:
      - model_training.img_height
      - model_training.img_width
      - model_training.learning_rate
    outs:
      - models/binaryclass/base_binary_model.keras
      - models/multiclass/base_multi_model.keras

  model_training:
    cmd: python -m src.components.model_training
    deps:
      - src/components/model_training.py
      - config/config.yaml
    params:
      - model_training.batch_size
      - model_training.epochs
      - model_training.learning_rate
    outs:
      - models/binaryclass/trained_binary_model.keras
      - models/multiclass/trained_multiclass_model.keras

  model_evaluation:
    cmd: python -m src.components.model_evaluation
    deps:
      - src/components/model_evaluation.py
      - config/config.yaml
