data_processing:
  test_size: 0.20
  random_state: 27
  target_mapping:
    0: 0
    1: 0
    2: 0
    3: 1
  relation_map:
    {0: 'Cyst',
    1: 'Normal',
    2: 'Stone',
    3: 'Tumor'}
  
model_architecture:
  base_model: "EfficientNetB0"
  include_top: false
  pooling: "max"
  dense_units: 64
  dropout_rate: 0.3
  activation: "relu"

basic_model_params:
  img_height: 224
  img_width: 224

binaryclass_model_params:
  is_binaryClassification: True
  metrics: ["accuracy"]
  loss: "binary_crossentropy"
  optimizer: "Adamax"
  num_classes: 2
  batch_size: 64
  epochs: 15
  learning_rate: 0.001
  experiment_name: binaryclass_CNNs
  run_name: EfficientNETB0_Evaluation_1

multiclass_model_params:
  is_binaryClassification: False
  metrics: ["accuracy"]
  loss: "sparse_categorical_crossentropy"
  optimizer: "Adamax"
  num_classes: 4
  batch_size: 64
  epochs: 25
  learning_rate: 0.001
  experiment_name: multiclass_CNNs
  run_name: EfficientNETB0_Evaluation_1