data_processing:
  test_size: 0.25
  random_state: 27
  target_mapping:
    0: 0
    1: 0
    2: 0
    3: 1
  relation_map:
    0: 'Cyst'
    1: 'Normal'
    2: 'Stone'
    3: 'Tumor'
  
model_building:
  metrics: ["accuracy"]
  binary_loss: "binary_crossentropy"
  multi_loss: "sparse_categorical_crossentropy"
  optimizer: "Adam"
  num_classes: 4

model_training:
  is_binaryClassification: False
  batch_size: 16
  img_height: 224
  img_width: 224
  epochs: 1
  learning_rate: 0.005