data_paths:
  raw_data_path: data/raw/kidneyData.csv
  train_data_path: data/final/train.csv
  test_data_path: data/final/test.csv
  images_dir: data/raw/images

artifacts_paths:
  binaryweights: models/binaryclass/binarymodel_weights.h5
  multiweights: models/multiclass/multimodel_weights.h5
  binarymetrics: reports/binaryclass/metrics.json
  multimetrics: reports/multiclass/metrics.json

descripts_path:
  class_descriptions_path : class_descriptions.json