data_processing:
  raw_data_path: data/raw/kidneyData.csv
  train_data_path: data/final/train.csv
  test_data_path: data/final/test.csv

model_building:
  base_model_path: models/base_model.keras

model_training:
  train_data_path: data/final/train.csv
  images_dir: data/raw/images
  base_model_path: models/base_model.keras
  trained_model_path: models/trained_model.keras

model_evaluation:
  test_data_path: data/final/test.csv
  images_dir: data/raw/images
  trained_model_path: models/trained_model.keras