data_paths:
  raw_data_path: data/raw/kidneyData.csv
  train_data_path: data/final/train.csv
  test_data_path: data/final/test.csv
  images_dir: data/raw/images

model_paths:
  base_binaryclass_model_path: models/binaryclass/base_binary_model.keras
  base_multiclass_model_path: models/multiclass/base_multi_model.keras
  trained_binaryclass_model_path: models/binaryclass/trained_binary_model.keras
  trained_multiclass_model_path: models/multiclass/trained_multi_model.keras

report_paths:
  binarymodel_metrics_path: reports/binaryclass/metrics.json
  multimodel_metrics_path: reports/multiclass/metrics.json